# ===== AUTO-GENERATED BY APP-KIT - DO NOT EDIT =====
# This file is managed by @mchen-lab/app-kit and will be
# overwritten when running `npx @mchen-lab/app-kit update`.
# Version: 0.1.12
# ====================================================

#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.."

# Find config file
if [ ! -f "./devops.config.json" ]; then
    echo "❌ Error: devops.config.json not found"
    exit 1
fi

# Read config values using node
read_config() {
    node -p "require('./devops.config.json').$1 || ''"
}

PROJECT_NAME=$(read_config "projectName")
GHCR_ORG=$(read_config "ghcrOrg")
DOCKERHUB_USER=$(read_config "dockerHubUser")
IMAGE_NAME=$(read_config "imageName")
BUILDER_NAME="${IMAGE_NAME}-builder"

# Check if Docker is running
if ! docker info > /dev/null 2>&1; then
    echo "❌ Error: Docker is not running or not accessible."
    exit 1
fi

# Image names
GHCR_IMAGE="ghcr.io/$GHCR_ORG/$IMAGE_NAME"
DOCKERHUB_IMAGE="$DOCKERHUB_USER/$IMAGE_NAME"
INPUT_TAG="${1:-dev}"

# Help
if [ "$1" == "--help" ]; then
    echo "Usage: ./devops/build_and_publish.sh [tag]"
    echo "       ./devops/build_and_publish.sh dev       # Build with 'dev' tag"
    echo "       ./devops/build_and_publish.sh v1.2.3    # Build with semver tags"
    echo ""
    echo "Project: $PROJECT_NAME"
    echo "Images:  $GHCR_IMAGE, $DOCKERHUB_IMAGE"
    exit 0
fi

# Tag logic
TAGS=""
add_tag() {
    local tag=$1
    TAGS="$TAGS -t $GHCR_IMAGE:$tag"
    if [ -n "$DOCKERHUB_USER" ]; then
        TAGS="$TAGS -t $DOCKERHUB_IMAGE:$tag"
    fi
}

if [[ "$INPUT_TAG" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
    MAJOR="${BASH_REMATCH[1]}"
    MINOR="${BASH_REMATCH[2]}"
    VERSION="$MAJOR.$MINOR.${BASH_REMATCH[3]}"
    
    echo "Detected version tag: v$VERSION"
    add_tag "$VERSION"
    add_tag "$MAJOR.$MINOR"
    add_tag "$MAJOR"
    add_tag "latest"
else
    add_tag "$INPUT_TAG"
fi

echo "=== 🐳 Building $PROJECT_NAME ==="
echo "Tags to push:"
echo "$TAGS" | sed 's/-t //g' | tr ' ' '\n'

# Setup buildx
if ! docker buildx inspect "$BUILDER_NAME" > /dev/null 2>&1; then
    echo "Creating new buildx builder..."
    docker buildx create --name "$BUILDER_NAME" --use
    docker buildx inspect --bootstrap
else
    docker buildx use "$BUILDER_NAME"
fi

PKG_VERSION=$(node -p "require('./package.json').version")
BUILD_META="${PKG_VERSION}-dev-$(date +%Y%m%d)"
COMMIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

docker buildx build \
  --platform linux/amd64,linux/arm64 \
  --build-arg BUILD_METADATA="$BUILD_META" \
  --build-arg GIT_COMMIT="$COMMIT_HASH" \
  $TAGS \
  --push \
  .

echo ""
echo "✅ Build and publish completed successfully!"
