# ===== AUTO-GENERATED BY APP-KIT - DO NOT EDIT =====
# This file is managed by @mchen-lab/app-kit and will be
# overwritten when running `npx @mchen-lab/app-kit update`.
# Version: 0.1.12
# ====================================================

FROM node:20-alpine AS builder

WORKDIR /app

# Copy package files
COPY package*.json ./

# Copy local libs
COPY libs ./libs

# Install all dependencies
RUN npm ci

# Copy source files
COPY . .

# Build arguments
ARG GIT_COMMIT
ARG BUILD_METADATA

# Set environment variables for build
ENV GIT_COMMIT=${GIT_COMMIT}
ENV BUILD_METADATA=${BUILD_METADATA}

# Build frontend (if exists)
RUN npm run build:frontend || echo "No frontend build"
RUN mkdir -p dist

# Build server
RUN npm run build:server

# Production stage
FROM node:20-alpine AS production

# Architecture support
ARG TARGETARCH

# Install basic tools
# Install basic tools and python
RUN apk add --no-cache ca-certificates python3 py3-pip

WORKDIR /app

# Create directories for persistence
RUN mkdir -p /app/data /app/logs && chmod 777 /app/data /app/logs

# Copy package files
COPY package*.json ./

# Copy local libs for production install
COPY libs ./libs

# Install only production dependencies
RUN npm ci --only=production

# Setup Python Service
COPY python_service ./python_service
# Create a venv equivalent or just install system wide in container? Alpine py3-pip installs to system.
# Use --break-system-packages if needed on newer pip, or just rely on apk packages if possible.
# But simplest is pip install requirements. 
RUN pip3 install --no-cache-dir -r python_service/requirements.txt --break-system-packages

# Copy built assets from builder
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/dist-server ./dist-server

# Expose port
EXPOSE 31160

# Set environment variables
ENV NODE_ENV=production
ENV PORT=31160
ENV DATA_DIR=/app/data
ENV LOGS_DIR=/app/logs
# Also pass build info to production for runtime API
ARG GIT_COMMIT
ARG BUILD_METADATA
ENV GIT_COMMIT=${GIT_COMMIT}
ENV BUILD_METADATA=${BUILD_METADATA}
ENV VITE_COMMIT_HASH=${GIT_COMMIT}
ENV VITE_APP_VERSION=${BUILD_METADATA}

# Start the server
CMD ["node", "dist-server/server/index.js"]
