/**
 * ===== AUTO-GENERATED BY APP-KIT - DO NOT EDIT =====
 * This file is managed by @mchen-lab/app-kit and will be
 * overwritten when running `npx @mchen-lab/app-kit update`.
 * Version: 0.1.12
 * ====================================================
 */

import { defineConfig } from "vite";
import path from "path";
import fs from "fs";
import { fileURLToPath } from "url";
import { execSync } from "child_process";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Read package.json
const packageJson = JSON.parse(fs.readFileSync(path.resolve(__dirname, "./package.json"), "utf-8"));

// Get commit hash
let commitHash = process.env.GIT_COMMIT;
if (!commitHash) {
  try {
    // Only try git if not provided via env (dev mode)
    // Redirect stderr to null to avoid "fatal: Needed a single revision" in new repos
    commitHash = execSync('git rev-parse --short HEAD 2>/dev/null').toString().trim();
  } catch (e) {
    commitHash = 'unknown';
  }
}

export default defineConfig({
  define: {
    '__APP_VERSION__': JSON.stringify('v' + packageJson.version + (process.env.BUILD_METADATA || '')),
    '__COMMIT_HASH__': JSON.stringify(commitHash),
  },
  plugins: [react(), tailwindcss()],
  root: "src/frontend",
  
  server: {
    middlewareMode: true,
  },

  build: {
    outDir: "../../dist",
    emptyOutDir: true,
  },

  resolve: {
    alias: {
      "@": path.resolve(__dirname, "src/frontend"),
    },
  },
});
